### ISSUE TITLE
关于保存json文件的建议

### ISSUE THREAD

**Issue by eagleLiu82** [pwxcoo/chinese-xinhua#1]
保存的json要是能加个汉字的key就好了，不然性能真有问题。

**Comment by wangzhe258369** [comment]
加载后重建以汉字为key的map呗

**Comment by pwxcoo** [comment]
dump 之后可以重建一下，我用的时候是 dump 到数据库里了。

因为考虑到多音字，以及当时为了方便我的调用，同一个汉字在数据库里是可能多条 records ，当时我用的没什么问题。。

**Comment by pwxcoo** [comment]
@caih1943 有是有，要整理一下，过几天上传。
