### ISSUE TITLE
你好，请与上海市徐汇分局联系

### ISSUE THREAD

**Issue by dreammis** [pwxcoo/chinese-xinhua#10]
算了，不要联系了，直接自己买付手铐过来吧，带点随身衣物，不要超过2公斤，门口有称重，超重罚款。
温馨提示，带个充电宝，否则你会无聊致死。

**Comment by pwxcoo** [comment]
自首从宽处理

**Comment by LiuWeiYi** [comment]
你确实是挺闲的啊




| |
柳维义
邮箱：valius@163.com
|

签名由 网易邮箱大师 定制

在2018年08月21日 21:30，PWXCOO 写道：

Closed #10.
