### ISSUE TITLE
貌似有重复的

### ISSUE THREAD

**Issue by gaizhixin** [pwxcoo/chinese-xinhua#11]
就拿兴高采烈来说 有两条数据 唯一不同的就是 example 字段的最后一句 也希望能对数据做一些优化处理 很不错的项目

**Comment by pwxcoo** [comment]
恩，之后会做一个清洗数据版本的。emmm，当然也要过段时间。。

**Comment by pwxcoo** [comment]
[update data: duplicate idioms removal](https://github.com/pwxcoo/chinese-xinhua/commit/8de1001aa499cd65fb97ef8712550188c0297a08) 处理了重复的成语。
