### ISSUE TITLE
ci.json格式有问题

### ISSUE THREAD

**Issue by loaderlin** [pwxcoo/chinese-xinhua#12]
### 用Visual Studio Code 打开ci.json有问题 
其他几个文件(iditom.json,word.json)打开会自动格式化(排版) ci.json不会

**Comment by pwxcoo** [comment]
因为我没格式化 = =。。。 `ci.json` 因为有点大，我自己格式化 `ci.json` 会卡住 = =，我就没格式化了。。数据本身并没有问题，其他文件只是因为比较小，我格式化完在 push 上去的。。

这个格式化不格式化并不影响数据读取的。

**Comment by loaderlin** [comment]
嗯，安装json-tool ，按Shift+Alt+F 格式化 是比较耗时间的。
