### ISSUE TITLE
数据源的问题？

### ISSUE THREAD

**Issue by jjeejj** [pwxcoo/chinese-xinhua#14]
您好，我想请教一下的 你抓取的数据源是什么网站呢？ 

我这边想做一个划词翻译的中文 的插件，想看看数据源的数据是长什么样的 ？ 在看看版权啊。 现在好多汉字都不认识  😅

**Comment by pwxcoo** [comment]
在 `scripts` 目录里的脚本文件写了目标网站，有好几个数据源。
