### ISSUE TITLE
nodejs架设中间件，请求https://www.pwxcoo.com/dictionary返回空数据

### ISSUE THREAD

**Issue by xizhouhezai** [pwxcoo/chinese-xinhua#15]
想做一个简单的前端页面，来显示查询结果，但是发生跨域问题，于是想用nodejs做个中间件，解决跨域问题，但是在用nodejs的http请求https://www.pwxcoo.com/dictionary这个接口时，返回的数据总是为空，在浏览器打开接口和在postman里测试这个接口都没问题，为什么在nodejs里请求会返回空数据？希望大佬解答一下，谢谢了

**Comment by pwxcoo** [comment]
- 跨域是因为我确实没做跨域的配置。。
- node 里返回的 HTTP 状态码是什么？

**Comment by xizhouhezai** [comment]
400，显示是成功返回，但是就是没有数据，是个空数组

**Comment by pwxcoo** [comment]
不不不，400 是无效请求，可能的原因是：
- 不是 `GET` 或 `POST`
- 没传参数

**Comment by xizhouhezai** [comment]
不好意思，打错了，是200

**Comment by pwxcoo** [comment]
这我也不知道了。。Postman 里可以的话，说明 http 是正常的，可能是你的 node 代码有问题，你可以再看看
