### ISSUE TITLE
中文参数被encodeURI转码后返回数据为空

### ISSUE THREAD

**Issue by Jamestoms** [pwxcoo/chinese-xinhua#17]
使用axios发送请求，例如查询成语‘兴高采烈’，查看控制台请求详情，汉字被encodeURI编码了，返回的数据为空，请问这个问题如何解决呢？我是新手，还望不吝赐教，非常感谢！

**Comment by Jamestoms** [comment]
用vue写的：
<style>

</style>
<template>
<div>
  <el-input v-model="searchWord" placeholder="请输入" @change="doSearch"></el-input>
  <div v-for="(item,index) in list" :key="index">
    <div><span>成语:</span><span>{{item.word}}</span></div>
    <div><span>拼音:</span><span>{{item.pinyin}}</span></div>
    <div><span>释义:</span><span>{{item.explanation}}</span></div>
    <div><span>出处:</span><span>{{item.derivation}}</span></div>
    <div><span>例句:</span><span>{{item.example}}</span></div>
  </div>
  <div v-if="list.length<1">{{tips}}</div>
</div>
</template>
<script>
export default {
  data(){
    return {
      list:[],
      searchWord:'',
      tips:''
    }
  },
  methods:{
    doSearch(){
      this.$http.get(**'/dictionary?type=idiom&abbreviation='+this.searchWord**).then((res)=>{
        Array.isArray(res.data)?(this.list = res.data):(this.list = [],this.tips = res.data.message);
        console.log(res)
      })
    }
  },
  created(){
    
  }
}
</script>

**Comment by Jamestoms** [comment]
vue写的，贴进来的html标签不能显示
<style>

</style>
<template>
<div>
  <el-input v-model="searchWord" placeholder="请输入" @change="doSearch"></el-input>
  <div v-for="(item,index) in list" :key="index">
    <div><span>成语:</span><span>{{item.word}}</span></div>
    <div><span>拼音:</span><span>{{item.pinyin}}</span></div>
    <div><span>释义:</span><span>{{item.explanation}}</span></div>
    <div><span>出处:</span><span>{{item.derivation}}</span></div>
    <div><span>例句:</span><span>{{item.example}}</span></div>
  </div>
  <div v-if="list.length<1">{{tips}}</div>
</div>
</template>
<script>
export default {
  data(){
    return {
      list:[],
      searchWord:'',
      tips:''
    }
  },
  methods:{
    doSearch(){
      this.$http.get('/dictionary?type=idiom&abbreviation='+this.searchWord).then((res)=>{
        Array.isArray(res.data)?(this.list = res.data):(this.list = [],this.tips = res.data.message);
        console.log(res)
      })
    }
  },
  created(){
    
  }
}
</script>

**Comment by Jamestoms** [comment]
![dictionary](https://user-images.githubusercontent.com/30195437/45020504-c0565600-b061-11e8-8913-f030803d7e5c.PNG)

**Comment by pwxcoo** [comment]
换一种写法试试，虽然我用的时候没遇到这种问题，但是感觉这个答案应该是你想要的。
- [How to prevent Axios from encoding my request parameters?](https://stackoverflow.com/questions/39116731/how-to-prevent-axios-from-encoding-my-request-parameters)

**Comment by Jamestoms** [comment]
好的，我看看，非常感谢你！
