### ISSUE TITLE
能否增加 {汉字 -> 拼音} API ？

### ISSUE THREAD

**Issue by chenakam** [pwxcoo/chinese-xinhua#18]
真是太棒了，但如果能增加 {汉字 -> 拼音} API 就更完美了。

给你个参考库，哈哈：
https://gitee.com/wei.chou/pinyin4j

**Comment by pwxcoo** [comment]
我提供的 API 服务已经下线啦。本身的数据库里就有 `pinyin` 字段，需要的话可以自己做二次处理。
