### ISSUE TITLE
数据请求次数

### ISSUE THREAD

**Issue by caoxingyu** [pwxcoo/chinese-xinhua#2]
接口请求次数有限制吗？还有能不能支持模糊查询？

**Comment by eagleLiu82** [comment]
这个也是我fork过来的，测试一下没什么限制。
歇后语支持模糊查询的。

**Comment by pwxcoo** [comment]
这个接口是我之前自己一个人在用的，没有什么限制，如果自己要比较严格的需求的话，可以自己用数据库做一层服务。

只有歇后语支持模糊查询，成语支持首字母缩写查询，如果都想做模糊的话，也可以自己拿数据做一下对应的功能。
