### ISSUE TITLE
使用jquery jsonp调用接口在控制台为什么输出空白呢？ 在网络请求里可以看到返回的数据。

### ISSUE THREAD

**Issue by Sunday-web** [pwxcoo/chinese-xinhua#21]
` $.ajax({
    type: "GET",
    url: "https://www.pwxcoo.com/dictionary?type=word&word=吴",
    dataType: "jsonp",
    success: function (result) { //成功的回调函数
      console.log('新华字典');
      console.log(result);
    }
  });`

**Comment by pwxcoo** [comment]
这个我也不知道诶，不过 API 服务下线啦，有需要的话可以自己下载数据集做处理和开发。
