### ISSUE TITLE
与商务出版社官方的新华字典数据差异

### ISSUE THREAD

**Issue by laytonwang** [pwxcoo/chinese-xinhua#22]
首先感谢楼主在资料整理上的辛苦和贡献，有没有研究过与商务出版社官方的新华字典数据差异？新华字典最权威的版本出自商务出版社，其它出版社多少都有点问题。我们想构建一个中文学习基础平台所以需要一份权威数据。如有答复将非常感谢！

**Comment by pwxcoo** [comment]
你好，因为这个仓库的数据是我从网上字典类网站抓取整理的，必然是和商务出版社官方的原始标准数据有所差异。（因为我没找到官方公开的数据集，貌似没公开？）所以这个仓库是不够权威的，并且部分数据可能有所错误和一些脏数据，不能保证绝对权威和正确。谢谢！

**Comment by laytonwang** [comment]
谢谢答复！辛苦了！
