### ISSUE TITLE
成语json数据重复

### ISSUE THREAD

**Issue by shuaixr** [pwxcoo/chinese-xinhua#24]
数据表设置为一键时发现，大约有1000个左右
没有统计大概有：
因材施教
愚不可及
雨打风吹(四次重复)
与世沉浮
于虎某皮
玉不琢，不成器(三次重复)
狱货非宝
玉叶金枝
浴血奋战
还用很多很多很多
建议过滤一下

**Comment by pwxcoo** [comment]
已去重。
