### ISSUE TITLE
没有词语的API吗？

### ISSUE THREAD

**Issue by P-huaizhi** [pwxcoo/chinese-xinhua#5]
好像没有说明词语的type

**Comment by pwxcoo** [comment]
是的，因为是不久前加的，最近也没时间，过段时间再说吧。

**Comment by whitefirer** [comment]
谢谢答主，加油！

**Comment by P-huaizhi** [comment]
嗯 辛苦啦！

**Comment by n3uz** [comment]
> 本仓库无任何商业目的！如果有侵权行为，请联系我！请不要把我抓走！

求生欲极强的UP主

**Comment by wanglefeifei** [comment]
牛逼啊 楼主

**Comment by pwxcoo** [comment]
emmm，我的服务器要到期了。。所以把 API 功能给下线了，如果有需求，可以自己下载数据集做二次开发，感谢理解！
