### ISSUE TITLE
不错！支持一波

### ISSUE THREAD

**Issue by kang558** [pwxcoo/chinese-xinhua#6]
支持一波！大佬三连：大佬佩服，大佬牛皮，仰慕大佬~ 加油！O(∩_∩)O哈哈~ 😂

**Comment by pwxcoo** [comment]
谢谢，但是这个东西真的没有技术含量，你这样让我很惭愧。

PS：说一句，虽然你这个 issue 并没有恶意，但是有灌水的嫌疑，issue 的作用并不是灌水，这种帖子不应该开个 issue，我 close 掉了，谢谢！

**Comment by kang558** [comment]
没有啊。😂
